# Python Programming: Intermediate

<img src="../images/OOP_1.jpg" alt="Python" style="width: 400px;"/>

# Program so far..
***
- Python Basics
- Python Programming Constructs
- Data Structures


# What are we going to learn today?
***
- Modular Programming in Python
    - Functions
    - Object Oriented Programming
- NumPy

# Modular Programming in Python
***
- Like all programming languages, Python provides various constructs to enable code reuse <br/><br/>

- Python provides functions/methods, classes and modules for reuse

<img src="../images/icon/Technical-Stuff.png" alt="Technical-Stuff" style="width: 100px;float:left; margin-right:15px"/>
<br />

## What is a function?
***

Formally, a function is a useful device that groups together a set of statements so they can be run more than once. They can also let us specify parameters that can serve as inputs to the functions.

On a more fundamental level, functions allow us to not have to repeatedly write the same code again and again. If you remember back to the lessons on strings and lists, remember that we used a function len() to get the length of a string. Since checking the length of a sequence is a common task you would want to write a function that can do this repeatedly at command.

Functions will be one of most basic levels of reusing code in Python, and it will also allow us to start thinking of program design (we will dive much deeper into the ideas of design when we learn about Object Oriented Programming).


## Function Definition
***
In the syntax below:
- **def** is the keyword used to define functions
- arg1...argn, \*args and \*\*kwargs are function parameters (and are optional)
- The expression after the `return` keyword is the value returned to the caller (optional)

Now lets look at how we can create a function in python

In [1]:
def name_of_function(arg1,arg2):
    '''
    This is where the function's Document String (doc-string) goes
    '''
    # Do stuff here
    #return desired result

## def Statements

We begin with def then a space followed by the name of the function. Try to keep names relevant, for example len() is a good name for a length() function. Also be careful with names, you wouldn't want to call a function the same name as a built-in function in Python (such as len).

Next come a pair of parenthesis with a number of arguments separated by a comma. These arguments are the inputs for your function. You'll be able to use these inputs in your function and reference them. After this you put a colon.

Now here is the important step, you must indent to begin the code inside your function correctly. Python makes use of whitespace to organize code. Lots of other programing languages do not do this, so keep that in mind.

Next you'll see the doc-string, this is where you write a basic description of the function. Using iPython and iPython Notebooks, you'll be ab;e to read these doc-strings by pressing Shift+Tab after a function name. Doc strings are not necessary for simple functions, but its good practice to put them in so you or other people can easily understand the code you write.

After all this you begin writing the code you wish to execute.

The best way to learn functions is by going through examples. So let's try to go through examples that relate back to the various objects and data structures we learned about before.

### Example 1: A simple print 'hello' function
In this example we take our first steps to write a working function which prints out 'hello'

In [2]:
def say_hello():
    print 'hello'

#call the function 

say_hello()

hello


## Function Arguments
***
- Parameters may or may not have default values (in the example, argn has default value 3)
- A function parameter can be passed either by position or by key/name
- A function can accept a variable number of positional arguments (\*args)
- A function can accept a variable number of keyword arguments (\*\*kwargs)
- Function parameters are passed by object reference


In [3]:
def function_name(arg1, arg2, argn=3, *args, **kwargs):
    print("This is a function.")
    # Function body here
    return value

### Default Arguments

Default arguements are those arguments which can be changed but their value remains the same if not given. An example of the same is given below.

In [4]:
def double_the_number(num=1):
    return num * 2

print(double_the_number())

2


<img src="../images/icon/ppt-icons.png" alt="Technical-Stuff" style="width: 100px;float:left; margin-right:15px"/>
<br />

### Mini Challenge
***
Its your turn now. Can you write a function square_root having default value of input a=9 and find the square-root of the same.

### Variable Arguments (1/2)

The special syntax *args in function definitions in python is used to pass a variable number of arguments to a function. It is used to pass a non-keyworded, variable-length argument list.

- The syntax is to use the symbol * to take in a variable number of arguments; by convention, it is often used with the word args.
- What *args allows you to do is take in more arguments than the number of formal arguments that you previously defined. With *args, any number of extra arguments can be tacked on to your current formal parameters (including zero extra arguments).

- For example : we want to make a multiply function that takes any number of arguments and able to multiply them all together. It can be done using *args.
Using the *, the variable that we associate with the * becomes an iterable meaning you can do things like iterate over it, run some higher order functions such as map and filter, etc. The example of the same is shown below.

In [6]:
def print_positional_arguments(num1, *args):
    print(type(args))
    print(args)

print_positional_arguments(1, 2, 3, 4, 5)

<type 'tuple'>
(2, 3, 4, 5)


### Variable Arguments (2/2)
The special syntax `**kwargs` in function definitions in python is used to pass a keyworded, variable-length argument list. We use the name kwargs with the double star. The reason is because the double star allows us to pass through keyword arguments (and any number of them).

- A keyword argument is where you provide a name to the variable as you pass it into the function.
- We can think of the kwargs as being a dictionary that maps each keyword to the value that we pass alongside it. That is why when we iterate over the kwargs there doesn’t seem to be any order in which they were printed out.

An Example of the same is shown below.


In [22]:
def print_keyword_arguments(num1, **kwargs):
    print(type(kwargs))
    print(kwargs)

print_keyword_arguments(1, num2=2, str3='String Input')

<type 'dict'>
{'str3': 'String Input', 'num2': 2}


## Return Values
***

A Return value is a value that is returned after performing a specific operation in a function. Some advantages and usecases of return values are as follows.
- Unlike some other languages, Python allows returning multiple values 
- However, the multiple values is just a tuple of values
- Because of this, the tuple can simply be 'opened' into multiple variables


Now lets look at a function returning multiple values.

In [61]:
def square_and_cube(num):
    return num**2, num**3

answer = square_and_cube(3)
print(answer)
print(type(answer))

square, cube = square_and_cube(3)
print(square)
print(cube)

(9, 27)
<type 'tuple'>
9
27


<img src="../images/icon/ppt-icons.png" alt="Technical-Stuff" style="width: 100px;float:left; margin-right:15px"/>
<br />
### Mini Challenge
***
Its your turn again. Can you write a function function_tuple that takes in two numbers a and b and returns the sum as well as the product of these numbers

<img src="../images/icon/Concept-Alert.png" alt="Technical-Stuff" style="width: 100px;float:left; margin-right:15px"/>
<br />

## Lambda
***
One of Pythons most useful (and for beginners, confusing) tools is the lambda expression. lambda expressions allow us to create "anonymous" functions. This basically means we can quickly make ad-hoc functions without needing to properly define a function using def.

Function objects returned by running lambda expressions work exactly the same as those created and assigned by defs. There is key difference that makes lambda useful in specialized roles:

**Lambda's body is a single expression, not a block of statements.**
* Python supports the creation of anonymous functions at runtime, using a construct called **`lambda`**
* This approach is most commonly used when passing a simple function as an argument to another function.
* Lambdas are generally used in conjunction with typical functional concepts like `filter()`, `map()` and `reduce()`.

Now Lets slowly break down a lambda expression by deconstructing a function:

In [1]:
def square(num):
    result = num**2
    return result
square(2)

4

We can actually write this in one line (although it would be bad style to do so)

In [2]:
def square(num): return num**2

This is the form a function that a lambda expression intends to replicate. A lambda expression can then be written as:

In [3]:
square_lambda = lambda num: num**2

square_lambda(2)

4

<img src="../images/icon/ppt-icons.png" alt="Technical-Stuff" style="width: 100px;float:left; margin-right:15px"/>
<br />
### Mini Challenge
***
Can you write a lambda function to add two numbers a and b. 

<img src="../images/icon/Technical-Stuff.png" alt="Technical-Stuff" style="width: 100px;float:left; margin-right:15px"/>
<br />
## Higher order functions
***
In Python, we treat functions as first class objects, allowing you to perform the operations on functions.

In [5]:
# this is a higher order function

def calculate(func, num1, num2):
    return func(num1, num2)

# call calculate with the add function
calculate(add_lambda, 1, 2)

3

<img src="../images/icon/Technical-Stuff.png" alt="Technical-Stuff" style="width: 100px;float:left; margin-right:15px"/>
<br />
### `map`
***
map() is a function that takes in two arguments: a function and a sequence iterable. In the form: map(function, sequence) **`map(function, sequence)`**

The first argument is the name of a function and the second a sequence (e.g. a list). map() applies the function to all the elements of the sequence. It returns a new list with the elements changed by function.

When we went over list comprehension we created a small expression to convert Fahrenheit to Celsius. Let's do the same here but use map.

We'll start with two functions:

In [6]:
def fahrenheit(T):
    return ((float(9)/5)*T + 32)
def celsius(T):
    return (float(5)/9)*(T-32)
    
temp = [0, 22.5, 40,100]

Now lets see map() in action:

In [7]:
F_temps = map(fahrenheit, temp)

#Show
F_temps

[32.0, 72.5, 104.0, 212.0]

In [8]:
# Convert back
map(celsius, F_temps)

[0.0, 22.5, 40.0, 100.0]

In the example above we haven't used a lambda expression. By using lambda, we wouldn't have had to define and name the functions fahrenheit() and celsius().

In [9]:
map(lambda x: (5.0/9)*(x - 32), F_temps)

[0.0, 22.5, 40.0, 100.0]

<img src="../images/icon/ppt-icons.png" alt="Technical-Stuff" style="width: 100px;float:left; margin-right:15px"/>
<br />
### Mini Challenge
***
Great! We got the same result! Using map is much more commonly used with lambda expressions since the entire purpose of map() is to save effort on having to create manual for loops.

map() can be applied to more than one iterable. The iterables have to have the same length.

For example lets map a lambda expression:


In [10]:
a = [1,2,3,4]
b = [5,6,7,8]
c = [9,10,11,12]

<img src="../images/icon/Technical-Stuff.png" alt="Technical-Stuff" style="width: 100px;float:left; margin-right:15px"/>
<br />
### `filter`
***

The function filter(function, list) offers a convenient way to filter out all the elements of an iterable, for which the function returns True. 

The function filter(function(),l) needs a function as its first argument. The function needs to return a Boolean value (either True or False). This function will be applied to every element of the iterable. Only if the function returns True will the element of the iterable be included in the result.

Lets see some examples:


In [11]:
numbers = list(range(10))

def is_even(x):
    return x % 2 == 0

is_even_lambda = lambda x: x % 2 == 0

print(filter(is_even, numbers))
print(filter(is_even_lambda, numbers))

[0, 2, 4, 6, 8]
[0, 2, 4, 6, 8]


<img src="../images/icon/Concept-Alert.png" alt="Concept-Alert" style="width: 100px;float:left; margin-right:15px"/>
<br />
## Nested Functions and Closures
***
- Python functions can be defined within the scope of another function.

- The inner function **definition** happens only when the outer function executes

- The inner function is only in scope inside the outer function, so it is often most useful when the inner function is being returned (or passed to another function)

- It is possible to return an inner function that "remembers" the state of the outer function has completed execution. This is called a closure.

In [12]:
# Nested Functions - function returning function
def outer(a):
    def inner(b):
        return a + b + 5
    return inner

twentyfive_adder = outer(20)
seven_adder = outer(2)


print(twentyfive_adder(5))
print(seven_adder(5))

30
12


<img src="../images/icon/Concept-Alert.png" alt="Concept-Alert" style="width: 100px;float:left; margin-right:15px"/>
<br />
# Object Oriented Programming
***

Object Oriented Programming (OOP) tends to be one of the major obstacles for beginners when they are first starting to learn Python.

There are many,many tutorials and lessons covering OOP so feel free to Google search other lessons, and I have also put some links to other useful tutorials online at the bottom of this Notebook.

For this lesson we will construct our knowledge of OOP in Python by building on the following topics:

* Objects
* Using the *class* keyword
* Creating class attributes
* Creating methods in a class
* Learning about Inheritance
* Learning about Special Methods for classes

Lets start the lesson by remembering about the Basic Python Objects. For example:

In [13]:
l = [1,2,3]

Remember how we could call methods on a list?

In [14]:
l.count(2)

1

What we will basically be doing in this lecture is exploring how we could create an Object type like a list. We've already learned about how to create functions. So lets explore Objects in general:

## Objects

In Python, everything is an object. Remember from previous lectures we can use type() to check the type of object something is:

In [15]:
print type(1)
print type([])
print type(())
print type({})

<type 'int'>
<type 'list'>
<type 'tuple'>
<type 'dict'>


So we know all these things are objects, so how can we create our own Object types? That is where the class keyword comes in.

## class
The user defined objects are created using the class keyword. The class is a blueprint that defines a nature of a future object. From classes we can construct instances. An instance is a specific object created from a particular class. For example, above we created the object 'l' which was an instance of a list object.

Let see how we can use class:

In [16]:
# Create a new object type called Sample
class Sample(object):
    pass

# Instance of Sample
x = Sample()

print type(x)

<class '__main__.Sample'>


By convention we give classes a name that starts with a capital letter. Note how x is now the reference to our new instance of a Sample class. In other words, we **instantiate** the Sample class.

Inside of the class we currently just have pass. But we can define class attributes and methods.

An **attribute** is a characteristic of an object.
A **method** is an operation we can perform with the object.

For example we can create a class called Dog. An attribute of a dog may be its breed or its name, while a method of a dog may be defined by a .bark() method which returns a sound.

Let's get a better understanding of attributes through an example.

## Attributes
The syntax for creating an attribute is:
    
    self.attribute = something
    
There is a special method called:

    __init__()

This method is used to initialize the attributes of an object. For example:

In [17]:
class Dog(object):
    def __init__(self,breed):
        self.breed = breed
        
sam = Dog(breed='Lab')
frank = Dog(breed='Huskie')

Lets break down what we have above.The special method

    __init__() 

is called automatically right after the object has been created:

    def __init__(self, breed):
Each attribute in a class definition begins with a reference to the instance object. It is by convention named self. The breed is the argument. The value is passed during the class instantiation.

     self.breed = breed
Now we have created two instances of the Dog class. With two breed types, we can then access these attributes like this:     

In [18]:
sam.breed

'Lab'

In [19]:
frank.breed

'Huskie'

Note how we don't have any parenthesis after breed, this is because it is an attribute and doesn't take any arguments.

In Python there are also class object attributes. These Class Object Attributes are the same for any instance of the class. For example, we could create the attribute species for the Dog class. Dogs (regardless of their breed,name, or other attributes will always be mammals. We apply this logic in the following manner:

In [20]:
class Dog(object):
    
    # Class Object Attribute
    species = 'mammal'
    
    def __init__(self,breed,name):
        self.breed = breed
        self.name = name

In [21]:
sam = Dog('Lab','Sam')

In [22]:
sam.name

'Sam'

Note that the Class Object Attribute is defined outside of any methods in the class. Also by convention, we place them first before the init.

In [23]:
sam.species

'mammal'

## Methods

Methods are functions defined inside the body of a class. They are used to perform operations with the attributes of our objects. Methods are essential in encapsulation concept of the OOP paradigm. This is essential in dividing responsibilities in programming, especially in large applications.

You can basically think of methods as functions acting on an Object that take the Object itself into account through its self argument.

Let's see the explanation and go through an example of creating a Circle class

<img src="../images/icon/Concept-Alert.png" alt="Concept-Alert" style="width: 100px;float:left; margin-right:15px"/>
<br />
### Explanation
***
- **`self`** is similar to the **`this`** pointer in other languages, except that (1) it needs to be explicitly passed as the first parameter of the instance method, and (2) it is not a reserved keyword

- The **`__init__`** method is an initializer (_not_ constructor) and called on instantiation

- The **`__str__`** method is equivalent to toString()

- The **`__repr__`** method defines how the object is represented on console

In [24]:
class Circle(object):
    pi = 3.14

    # Circle get instantiated with a radius (default is 1)
    def __init__(self, radius=1):
        self.radius = radius 

    # Area method calculates the area. Note the use of self.
    def area(self):
        return self.radius * self.radius * Circle.pi

    # Method for resetting Radius
    def setRadius(self, radius):
        self.radius = radius

    # Method for getting radius (Same as just calling .radius)
    def getRadius(self):
        return self.radius


c = Circle()

c.setRadius(2)
print 'Radius is: ',c.getRadius()
print 'Area is: ',c.area()

Radius is:  2
Area is:  12.56


<img src="../images/icon/ppt-icons.png" alt="ppt-icons" style="width: 100px;float:left; margin-right:15px"/>
<br />
Great! Notice how we used self. notation to reference attributes of the class within the method calls. Review how the code above works and try creating your own method

# Inheritance
Inheritance is a way to form new classes using classes that have already been defined. The newly formed classes are called derived classes, the classes that we derive from are called base classes. Important benefits of inheritance are code reuse and reduction of complexity of a program. The derived classes (descendants) override or extend the functionality of base classes (ancestors).

Lets see an example on Employee's:

In [25]:
class Employee(object):
    def __init__(self, name, pay_rate):
        self.name = name
        self.pay_rate = pay_rate

    def __str__(self):
        return self.name + ", " + str(self.pay_rate)

    def pay(self, hours_worked):
        return self.pay_rate * hours_worked

class Manager(Employee):
    def __init__(self, name, pay_rate, is_salaried):
        super(Manager, self).__init__(name, pay_rate)
        self.is_salaried = is_salaried

    def __str__(self):
        return Employee.__str__(self) + " salaried: " + str(self.is_salaried)

    # Override method
    def pay(self, hours_worked):
        if self.is_salaried:
            return self.pay_rate
        else:
            return super(Manager, self).pay(hours_worked)

In [26]:
e1 = Employee("John Jones", 10.00)
print(e1)
print("Gross pay: " + str(e1.pay(40)))

m1 = Manager("Jane Smith", 1200, True)
print(m1)
print("Gross pay: " + str(m1.pay(40)))

m2 = Manager("Jim Brown", 20.00, False)
print(m2)
print("Gross pay: " + str(m2.pay(40)))

John Jones, 10.0
Gross pay: 400.0
Jane Smith, 1200 salaried: True
Gross pay: 1200
Jim Brown, 20.0 salaried: False
Gross pay: 800.0


Great! you should have a basic understanding of how to create your own objects with class in Python. You will be utilizing this heavily in your upcomming projects!

<img src="../images/icon/Concept-Alert.png" alt="Concept-Alert" style="width: 100px;float:left; margin-right:15px"/>
<br />
## Instance vs Class vs Static Methods
***
- Instance methods have access to the **instance** of the class
- Class methods have access to the **class** (classes are also objects in Python), but not instances. This is similar to the static methods in Java/C#
- Static methods have no access to either instances or classes. They are more like plain functions, just bounded with the class for scoping

In [27]:
class MyClass:
    def instance_method(self):
        print('instance method called', self)

    @classmethod
    def class_method(cls):
        print('class method called', cls)

    @staticmethod
    def static_method():
        print('static method called')

obj = MyClass()

obj.instance_method()
MyClass.class_method()
MyClass.static_method()

('instance method called', <__main__.MyClass instance at 0x107fe1560>)
('class method called', <class __main__.MyClass at 0x107f41a10>)
static method called


<img src="../images/icon/Technical-Stuff.png" alt="Technical-Stuff" style="width: 100px;float:left; margin-right:15px"/>
<br />
## Duck Typing
***
- It is a feature of dynamic languages
- Central idea: If it walks like a duck and quacks like a duck then treat it like a duck.
- This is why Python doesn't have "interfaces", just "protocols"

In [28]:
class Duck(object):
    def quack(self):
        print ('quack! quack!')
    
    def fly(self):
        print ('flap! flap!')

class Person(object):
    def quack(self):
        print ("I'm quacking like a duck!")
        
    def fly(self):
        print ("I'm flapping my arms!")

def quack_and_fly(thing):
    #if isinstance(thing, Duck)
    thing.quack()
    thing.fly()

quack_and_fly(Duck())
quack_and_fly(Person())

quack! quack!
flap! flap!
I'm quacking like a duck!
I'm flapping my arms!


# Python Intermediate: NumPy Basics

![caption](../images/numpy-logo.jpg)
***
NumPy, which stands for Numerical Python, is a library consisting of multidimensional array objects and a collection of routines for processing those arrays. Using NumPy, mathematical and logical operations on arrays can be performed. Let's along with the basics of NumPy such as its architecture and environment. It also discusses the various array functions, types of indexing, etc.

We can install numpy by `pip install numpy`

- Main object: **`ndarray`**

<img src="../images/icon/Technical-Stuff.png" alt="Technical-Stuff" style="width: 100px;float:left; margin-right:15px"/>
<br />
# ndarray
***

The most important object defined in NumPy is an N-dimensional array type called ndarray. It describes the collection of items of the same type. Items in the collection can be accessed using a zero-based index.

Every item in an ndarray takes the same size of block in the memory. Each element in ndarray is an object of data-type object (called dtype).Any item extracted from ndarray object (by slicing) is represented by a Python object of one of array scalar types. An instance of ndarray class can be constructed by different array creation routines described later.

You import the function in python by calling `import numpy`. The basic ndarray is created using an array function in NumPy as follows −

In [29]:
import numpy
numpy.array

<function numpy.core.multiarray.array>


<img src="../images/icon/Concept-Alert.png" alt="Concept-Alert" style="width: 100px;float:left; margin-right:15px"/>
<br />
## How do I create Arrays in Python?
***
* Create an array from a regular Python list or tuple using the array function. 

* The type of the resulting array is deduced from the type of the elements in the sequences

It creates an ndarray from any object exposing array interface, or from any method that returns an array.

In [30]:
numpy.array(object, dtype = None, copy = True, order = None, subok = False, ndmin = 0)

array(<type 'object'>, dtype=object)

In [31]:
import numpy as np

# From list: 1d array
my_list = [10, 20, 30]
np.array(my_list)

array([10, 20, 30])

In [32]:
# From list: 2d array

list_of_lists =  [[5, 10, 15], [20, 25, 30], [35, 40, 45]]
np.array(list_of_lists)

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [33]:
type(np.array(list_of_lists))

numpy.ndarray

An example of how does n-dimensional looks

## Types

![NumPy Array Types](../images/numpy-types1.jpg)

`ndarray` is also known by the alias `array`. Note that `numpy.array` is not the same as the Standard Python Library class `array.array`, which only handles one-dimensional arrays and offers less functionality. The more important attributes of an `ndarray` object are:

***ndarray.ndim***
the number of axes (dimensions) of the array. In the Python world, the number of dimensions is referred to as rank.

***ndarray.shape***
the dimensions of the array. This is a tuple of integers indicating the size of the array in each dimension. For a matrix with n rows and m columns, `shape` will be `(n,m)`. The length of the `shape` tuple is therefore the rank, or number of dimensions,`ndim`.

***ndarray.size***
the total number of elements of the array. This is equal to the product of the elements of shape.

***ndarray.dtype***
an object describing the type of the elements in the array. One can create or specify dtype’s using standard Python types. Additionally NumPy provides types of its own. numpy.int32, numpy.int16, and numpy.float64 are some examples.

***ndarray.reshape***
Returns an array containing the same data with a new shape.

<img src="../images/icon/Technical-Stuff.png" alt="Technical-Stuff" style="width: 100px;float:left; margin-right:15px"/>
<br />
## numpy.dtype
***
<br/>
The data type or dtype describes the kind of elements that are contained within the array.

* **bool**: Boolean values
<br/><br/>

* **int**: Integer values. Can be int16, int32, or int64.


* **float**: Floating point values. Can be float16, float32, or float64.
<br/><br/>


* ** string**: Text. Can be string or unicode (this distinction is greatly simplified in Python 3)

<img src="../images/icon/ppt-icons.png" alt="ppt-icons" style="width: 100px;float:left; margin-right:15px"/>
<br />
***
## Let's try it ourselves!
***
### Create a vector from the list [10, 20, 30]. Print the dtype and shape.

In [34]:
my_list = [10, 20, 30]

arr = np.array(my_list)

print(arr.dtype)
print(arr.shape)

int64
(3,)


<img src="../images/icon/ppt-icons.png" alt="ppt-icons" style="width: 100px;float:left; margin-right:15px"/>
<br />
***
### Create a matrix from the list of lists [[5.3, 10.2, 15.1], [20.4, 25.3, 30.9], [35.4, 40.1, 45.6]]. Print the dtype and shape. 

### Important Concepts
***
#### Rank

NumPy’s main object is the homogeneous multidimensional array. It is a table of elements (usually numbers), all of the same type, indexed by a tuple of positive integers. In NumPy dimensions are called axes. The number of axes is rank.

For example, the coordinates of a point in 3D space [1, 2, 1] is an array of rank 1, because it has one axis. That axis has a length of 3. 

In the example below, the array has rank 2 (it is 2-dimensional). The first dimension (axis) has a length of 2, the second dimension has a length of 6.

In [35]:
a =  np.array([[1, 2, 3,4,5,6],[7,8,9,10,11,12]]) 
print(a)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [36]:
print(a.shape)

(2, 6)


In [38]:
print(np.ndim(a))

2


# NumPy Built-in methods

## `arange`
***
arange(**[start,]** ***stop[, step,][, dtype]***) : Returns an array with evenly spaced elements as per the interval. The interval mentioned is half opened i.e. **[Start, Stop)** (similar to the Python **`range()`** function).

In [39]:
import numpy as np

np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## `zeros` and `ones`
***
Generate arrays of all zeros and ones

In [40]:
np.zeros((2, 3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [41]:
np.ones((2, 5))

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

## `eye`
***
Creates an identity matrix of given size

In [42]:
np.eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

## `linspace`
***
Linspace: Return **evenly spaced** numbers over a specified interval.

    linspace(start, stop, num=50, endpoint=True, retstep=False)

* Will return `num` number of values
* Equally spaced samples in the closed interval [start, stop] or the half-open interval [start, stop)
* Closed or half-open interval depends on whether 'endpoint' is True or False.

In [43]:
# divide into 7 interval from 0 to 10
np.linspace(0, 10, 7)

array([  0.        ,   1.66666667,   3.33333333,   5.        ,
         6.66666667,   8.33333333,  10.        ])

<img src="../images/icon/Concept-Alert.png" alt="Concept-Alert" style="width: 100px;float:left; margin-right:15px"/>
<br />
## How do I generate Random Numbers?
***
<br/>
Numpy also has lots of ways to create random number arrays of given shape

- **`rand`**:

`numpy.random.rand(d0, d1, …, dn)` Create an array of the given shape and populate it with random samples from a **uniform distribution**

- **`randn`**: 

`numpy.random.randn(d0, d1, …, dn)`creates an array of specified shape and fills it with random values as per **standard normal distribution**.

If positive arguments are provided, randn generates an array of shape (d0, d1, …, dn), filled with random floats sampled from a univariate “normal” (Gaussian) distribution of mean 0 and variance 1 (if any of the d_i are floats, they are first converted to integers by truncation).

A single float randomly sampled from the distribution is returned if no argument is provided.

- **`randint`**: 

Return random integers from the “discrete uniform” distribution of the specified dtype in the “half-open” interval [low, high). If high is None (the default), then results are from [0, low).

In [44]:
# random number (uniform distribution) array of shape (5, 5)

np.random.rand(3, 4)

array([[ 0.98723719,  0.27977444,  0.36217167,  0.51239744],
       [ 0.88249281,  0.76137804,  0.39485289,  0.09073534],
       [ 0.43164014,  0.41684202,  0.22017851,  0.08392155]])

In [45]:
# random number (standard normal distribution) array of shape (2, 3)

print (np.random.randn(2, 3))

[[-0.50712953 -0.0459861   0.90274606]
 [ 0.54849607  0.17119001 -0.58995648]]


In [46]:
# 10 random integers between 4 (inclusive) to 40 (exclusive)

np.random.randint(4, 40, 10)

array([20, 23,  7, 11, 34, 20, 14, 11, 27, 33])

In [47]:
# 10 random integers upto 50 (exclusive). This makes the start value default to 0.
# The size parameter dictates the return array shape

np.random.randint(50, size=(3,4))

array([[33, 39, 13,  2],
       [49, 36,  1,  0],
       [ 4,  0, 26, 38]])

<img src="../images/icon/ppt-icons.png" alt="ppt-icons" style="width: 100px;float:left; margin-right:15px"/>
<br />
***
Lets try to create a ndimensions array from randomly genrated numbers of (3,4), then rehape the array to (4,3)


# Analyzing the Weather using NumPy

<center><img src="../images/weather.jpg" alt="Weather" style="width: 350px;"/></center>
Now it's time to use some them to learn data manipulation by analyzing a weather data set. As they say

We'll be working with **weather_small_2012.csv**, which contains weather data for each hour in 2012.
Since weather_small_2012.csv is a csv file, rows are separated by line breaks, and columns are
separated by commas:

```
Date/Time,Temp (C),Dew Point Temp (C),Rel Hum (%),Wind Spd (km/h),Visibility (km),Stn Press (kPa)
2012-01-01 00:00:00,-1.8,-3.9,86,4,8.0,101.24
2012-01-01 01:00:00,-1.8,-3.7,87,4,8.0,101.24
2012-01-01 02:00:00,-1.8,-3.4,89,7,4.0,101.26
2012-01-01 03:00:00,-1.5,-3.2,88,6,4.0,101.27
```

**To read csv file, we use:**

    numpy.genfromtxt(fileName, delimeter=",")

In [48]:
# read csv file
weather = np.genfromtxt("../data/weather_small_2012.csv", delimiter=",")

print (weather.dtype)
print (weather)

float64
[[    nan     nan     nan ...,     nan     nan     nan]
 [    nan   -1.8    -3.9  ...,    4.      8.    101.24]
 [    nan   -1.8    -3.7  ...,    4.      8.    101.24]
 ..., 
 [    nan   -0.5    -1.5  ...,   28.      4.8    99.95]
 [    nan   -0.2    -1.8  ...,   28.      9.7    99.91]
 [    nan    0.     -2.1  ...,   30.     11.3    99.89]]


Many items in this dataset are nan.

* The entire first row is nan – headers are String.
* Some of the numbers are written like 1.98600000e+03.

The data type of world_milk is float. Because all of the values in a NumPy array have to have the same
data type, NumPy attempted to convert all of the columns to floats when they were read in.

** Reading In The Data Properly **

***
To read world_milk.csv file properly we will have to use correct data type and skip the header.
* genfromtxt() default dtype is float, it converts non-numeric value to nan (not a number)
* To avoid nan, we read values as |S20 (String of length 20) 

In [49]:
weather = np.genfromtxt("../data/weather_small_2012.csv", dtype='|S20', skip_header=1, delimiter=",")

print (weather.dtype)
print (weather[0])

|S20
['2012-01-01 00:00:00' '-1.8' '-3.9' '86' '4' '8.0' '101.24']


In [50]:
# Create an array of temperatures from the data set

temperatures = weather[:,1].astype(np.float16)
print(temperatures)

dew_point_temperatures = weather[:,2].astype(np.float16)
print(dew_point_temperatures)

[-1.79980469 -1.79980469 -1.79980469 ..., -0.5        -0.19995117  0.        ]
[-3.90039062 -3.69921875 -3.40039062 ..., -1.5        -1.79980469
 -2.09960938]


<img src="../images/icon/Concept-Alert.png" alt="Concept-Alert" style="width: 100px;float:left; margin-right:15px"/>
<br />
# Operations with NumPy arrays
<br/>
***
NumPy provides a lot of built-in functionality for working with arrays.
**The important concepts to remember are**
- Any operation with a scalar number or a scalar function will cause that operation being computed for each element
- Any operation with two **compatible** (eg.: same shape) arrays will cause one-to-one element computations

<img src="../images/icon/Maths-Insight.png" alt="Technical-Stuff" style="width: 100px;float:left; margin-right:15px"/>
<br />
## Arithmetic (1/2)
***
### Vector Arithmetic
- All operations between arrays are **element-wise**
- This means that if you multiply two 2d vectors, it will **NOT** perform matrix multiplication

<img src="../images/icon/Maths-Insight.png" alt="Technical-Stuff" style="width: 100px;float:left; margin-right:15px"/>
<br />
## Arithmetic (2/2)
***
### Scalar Arithmetic
- Any operation of an array with a scalar will result in **element-wise** computation of that operation
- For example **`my_array + 2`** is the same as adding 2 to each element of array

### Calculate the Temperatures from the weather dataset in Farenheit

In [51]:
farenheit = (temperatures * 9 / 5) + 32
farenheit

array([ 28.765625,  28.765625,  28.765625, ...,  31.09375 ,  31.640625,
        32.      ], dtype=float16)

In [52]:
# Using default Python list
farenheit2 = [(celcius * 9 / 5) + 32 for celcius in temperatures]
farenheit2[:5]

[28.760351562499999,
 28.760351562499999,
 28.760351562499999,
 29.300000000000001,
 29.300000000000001]

### Addition

In [53]:
# Total temperature

# Vector Addition
print(temperatures + dew_point_temperatures)

# Scalar Addition
print(temperatures + 100)

[-5.69921875 -5.5        -5.19921875 ..., -2.         -2.         -2.09960938]
[  98.1875   98.1875   98.1875 ...,   99.5      99.8125  100.    ]


### Division

In [54]:
array1 = np.arange(1, 10, dtype=np.float16).reshape(3, 3)
array2 = np.arange(100, 109, dtype=np.float16).reshape(3, 3)

print(array1)
print(array2)

print(array2 / array1)  # Vector Division
print(array2 / 3)    # Scalar Division

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]]
[[ 100.  101.  102.]
 [ 103.  104.  105.]
 [ 106.  107.  108.]]
[[ 100.         50.5        34.      ]
 [  25.75       20.796875   17.5     ]
 [  15.140625   13.375      12.      ]]
[[ 33.34375  33.65625  34.     ]
 [ 34.34375  34.65625  35.     ]
 [ 35.34375  35.65625  36.     ]]


## Comparison

Comparing two numpy arrays for equality, element-wise

In [55]:
# Find those temperatures that are above 0 degrees Celcius

greater_than_0 = temperatures > 0

print(temperatures)
print(greater_than_0)

print(type(greater_than_0))
print(greater_than_0.dtype)

[-1.79980469 -1.79980469 -1.79980469 ..., -0.5        -0.19995117  0.        ]
[False False False ..., False False False]
<type 'numpy.ndarray'>
bool


In [56]:
# multiple conditions
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

two_or_five = (arr == 2) | (arr == 5)
print(two_or_five)

[[False  True False]
 [False  True False]
 [False False False]]


In [57]:
arr1 = np.random.randint(1, 10, 6).reshape(2, 3)
arr2 = np.random.randint(1, 10, 6).reshape(2, 3)

print(arr1)
print(arr2)

print(arr1 >= arr2)

[[4 3 1]
 [3 7 6]]
[[8 2 9]
 [1 8 5]]
[[False  True False]
 [ True False  True]]


<img src="../images/icon/Technical-Stuff.png" alt="Concept-Alert" style="width: 100px;float:left; margin-right:15px"/>
<br />
## Aggregation 
* **`sum()`:** Computes the sum of all the elements in a vector, or the sum along a dimension in a matrix.
* **`mean()`:** Computes the average of all the elements in a vector, or the average along a dimension in a matrix.
* **`max()`/`min()`:** Identifies the maximum/minimum value among all the elements in a vector, or along a dimension in a matrix.
* **`argmax()`/`argmin()`:** Returns the index of maximum/minimum element.

In [58]:
# Find max, min, mean temperature
print('Max: ', temperatures.max())
print('Min: ', temperatures.min())
print('Mean: ', temperatures.mean())

# Find index of max/min temperature
print('Argmax: ', temperatures.argmax())
print('Argmin: ', temperatures.argmin())

('Max: ', 33.0)
('Min: ', -23.297)
('Mean: ', 8.7969)
('Argmax: ', 4143)
('Argmin: ', 344)


<img src="../images/icon/Maths-Insight.png" alt="Technical-Stuff" style="width: 100px;float:left; margin-right:15px"/>
<br />
## Mathematical Functions
***
Standard mathematical functions like `sin`, `cos`, `ceil`, etc are available in NumPy in vectorized form.

In [59]:
arr = np.random.randint(100, size=9).reshape(3, 3)

print(arr)
print(np.sin(arr))

[[46 49 14]
 [60 84  4]
 [ 8 86 26]]
[[ 0.90178835 -0.95375265  0.99060736]
 [-0.30481062  0.73319032 -0.7568025 ]
 [ 0.98935825 -0.92345845  0.76255845]]


<img src="../images/icon/Maths-Insight.png" alt="Technical-Stuff" style="width: 100px;float:left; margin-right:15px"/>
<br />
## Custom Vectorized Functions
***

In [60]:
x = np.random.randn(10)
print (x)

def my_func(x):
    return 1 if x > 0 else 0

vectorized_func = np.vectorize(my_func)
vectorized_func(x)

[-0.44101881  0.32225245  0.01161046  0.74217662  1.09500584  2.17083039
  1.04999057 -1.28169094  0.51068084  0.20593794]


array([0, 1, 1, 1, 1, 1, 1, 0, 1, 1])

# Further Reading
***
- Python Official Documentation: https://docs.python.org/
- NumPy documentation: http://www.numpy.org/

<img src="../images/icon/Recap.png" alt="Recap" style="width: 100px;float:left; margin-right:15px"/>
<br />
# In-session Recap Time
***
- Modular Programming in Python
    - Functions
    - OOP: Classes, Inheritance

- NumPy
    - Creating Arrays
    - Built-in Methods
    - Data Manipulation
    - Operations: Reshaping, Arithmetic, Aggregation, etc.

# Thank You
***
### Coming up next...

- Numpy Advanced: Indexing and Selection
- Introduction to Pandas

For more queries - Reach out to academics@greyatom.com 